#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 09, 2018 01:05:43 PM

import sys
import os
import json
import tkinter as tk
from tkinter import filedialog

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GMPEhandler_support



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = GMPE_File_Editor (root)
    GMPEhandler_support.init(root, top)
    root.mainloop()

w = None
def create_GMPE_File_Editor(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = GMPE_File_Editor (w)
    GMPEhandler_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_GMPE_File_Editor():
    global w
    w.destroy()
    w = None




#Example
bsData1 = { #Default bsData
    1: {
        "branchSetID": "bs1",
        "applyToTectonicRegionType": "Active Shallow Fault",
    }
}
ltBranch1 = { #Default ltBranch
    1: {
        1: {
            "branchSetID": "b11",
            "text": "GMPETable",
            "gmpe_table": "../gm_tables/WcrustFRjb_low_clC.hdf5",
            "uncertaintyWeight": "0.2"
        }
    }
}
ltData1 = { #Default ltData
    1: {
        "branchingLevelID": "bl1",
        "ltBranch": ltBranch1,
        "bsData": bsData1
    }
}

#Real Thing
bsData = { #Default bsData
}
ltBranch = { #Default ltBranch
}
ltData = { #Default ltData
}


def parseOut(Data):
    es = ""
    for x in range(0,len(Data)): #Parse the Branch Sets!!!
        x=x+1
        curBlock = Data[x]
        bsData2 = curBlock["bsData"][x]
        es = es+"\n Branch Set "+str(x)+" (Branch Set ID:  "+bsData2["branchSetID"]+") (Branching Level ID: "+curBlock["branchingLevelID"]+") (Tectonic Region Type: "+bsData2["applyToTectonicRegionType"]+")"
        for z in range(0, len(curBlock["ltBranch"][x])): #Parse each branch set's branches
            z = z+1
            curChild = curBlock["ltBranch"][x][z]
            es = es+"\n    -> Branch "+str(z)+" (Branch ID: "+curChild["branchSetID"]+") (GMPE Table: "+curChild["gmpe_table"]+") (Uncertainty Weight: "+curChild["uncertaintyWeight"]+")"
        print(es)
    pToOutput(es)

#POPUP WINDOW
def nbsPopup(): #New Branch Set Popup Window
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        style = ttk.Style()
        if sys.platform == "win32":
            style.theme_use('winnative')
        style.configure('.',background=_bgcolor)
        style.configure('.',foreground=_fgcolor)
        style.configure('.',font="TkDefaultFont")
        style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        top = tk.Tk()
        top.geometry("425x154+387+368")
        top.title("Create New Branch Set")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        #branch set txt label
        bsIDtxt = ttk.Label(top)
        bsIDtxt.place(relx=0.01, rely=0.06, height=20, width=86)
        bsIDtxt.configure(background="#d9d9d9")
        bsIDtxt.configure(foreground="#000000")
        bsIDtxt.configure(font="TkDefaultFont")
        bsIDtxt.configure(relief=FLAT)
        bsIDtxt.configure(text='''Branch Set ID''')
        #branch set id txt box
        bsIDbox = ttk.Entry(top)
        bsIDbox.place(relx=0.54, rely=0.06, relheight=0.13, relwidth=0.45)
        bsIDbox.configure(takefocus="")
        bsIDbox.configure(cursor="ibeam")

        blIDtxt = ttk.Label(top)
        blIDtxt.place(relx=0.01, rely=0.26, height=19, width=136)
        blIDtxt.configure(background="#d9d9d9")
        blIDtxt.configure(foreground="#000000")
        blIDtxt.configure(font="TkDefaultFont")
        blIDtxt.configure(relief=FLAT)
        blIDtxt.configure(text='''Branching Level ID''')

        blIDbox = ttk.Entry(top)
        blIDbox.place(relx=0.54, rely=0.26, relheight=0.13, relwidth=0.45)
        blIDbox.configure(takefocus="")
        blIDbox.configure(cursor="ibeam")

        attrtTXT = ttk.Label(top)
        attrtTXT.place(relx=0.28, rely=0.45, height=19, width=180)
        attrtTXT.configure(background="#d9d9d9")
        attrtTXT.configure(foreground="#000000")
        attrtTXT.configure(font="TkDefaultFont")
        attrtTXT.configure(relief=FLAT)
        attrtTXT.configure(text='''Apply To Tectonic Region Type''')

        attrtBOX = ttk.Entry(top)
        attrtBOX.place(relx=0.01, rely=0.58, relheight=0.13, relwidth=0.98)
        attrtBOX.configure(takefocus="")
        attrtBOX.configure(cursor="ibeam")


        createButton = Button(top)
        createButton.place(relx=0.39, rely=0.78, height=25, width=90)
        createButton.configure(activebackground="#d9d9d9")
        createButton.configure(activeforeground="#000000")
        createButton.configure(background="#d9d9d9")
        createButton.configure(disabledforeground="#a3a3a3")
        createButton.configure(foreground="#000000")
        createButton.configure(highlightbackground="#d9d9d9")
        createButton.configure(highlightcolor="black")
        createButton.configure(pady="0")
        createButton.configure(relief=GROOVE)
        createButton.configure(text='''Create''')
        def onClick():
            newBranchSet(bsIDbox.get(), attrtBOX.get(), blIDbox.get())
            top.destroy()
        createButton.configure(command=onClick)

def nbPopup(): #New Branch Set Popup Window
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        style = ttk.Style()
        if sys.platform == "win32":
            style.theme_use('winnative')
        style.configure('.',background=_bgcolor)
        style.configure('.',foreground=_fgcolor)
        style.configure('.',font="TkDefaultFont")
        style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        top = tk.Tk()
        top.geometry("425x154+387+368")
        top.title("Create New Branch")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        #branch set txt label
        bsIDtxt = ttk.Label(top)
        bsIDtxt.place(relx=0.01, rely=0.06, height=20, width=86)
        bsIDtxt.configure(background="#d9d9d9")
        bsIDtxt.configure(foreground="#000000")
        bsIDtxt.configure(font="TkDefaultFont")
        bsIDtxt.configure(relief=FLAT)
        bsIDtxt.configure(text='Branch Set ID')
        #branch set id txt box
        bsIDbox = ttk.Entry(top)
        bsIDbox.place(relx=0.54, rely=0.06, relheight=0.13, relwidth=0.45)
        bsIDbox.configure(takefocus="")
        bsIDbox.configure(cursor="ibeam")

        blIDtxt = ttk.Label(top)
        blIDtxt.place(relx=0.01, rely=0.26, height=19, width=136)
        blIDtxt.configure(background="#d9d9d9")
        blIDtxt.configure(foreground="#000000")
        blIDtxt.configure(font="TkDefaultFont")
        blIDtxt.configure(relief=FLAT)
        blIDtxt.configure(text='Uncertainty Weight')

        blIDbox = ttk.Entry(top)
        blIDbox.place(relx=0.54, rely=0.26, relheight=0.13, relwidth=0.45)
        blIDbox.configure(takefocus="")
        blIDbox.configure(cursor="ibeam")

        attrtTXT = ttk.Label(top)
        attrtTXT.place(relx=0.42, rely=0.45, height=19, width=180)
        attrtTXT.configure(background="#d9d9d9")
        attrtTXT.configure(foreground="#000000")
        attrtTXT.configure(font="TkDefaultFont")
        attrtTXT.configure(relief=FLAT)
        attrtTXT.configure(text='''gmpe_table''')

        attrtBOX = ttk.Entry(top)
        attrtBOX.place(relx=0.01, rely=0.58, relheight=0.13, relwidth=0.98)
        attrtBOX.configure(takefocus="")
        attrtBOX.configure(cursor="ibeam")


        createButton = Button(top)
        createButton.place(relx=0.39, rely=0.78, height=25, width=90)
        createButton.configure(activebackground="#d9d9d9")
        createButton.configure(activeforeground="#000000")
        createButton.configure(background="#d9d9d9")
        createButton.configure(disabledforeground="#a3a3a3")
        createButton.configure(foreground="#000000")
        createButton.configure(highlightbackground="#d9d9d9")
        createButton.configure(highlightcolor="black")
        createButton.configure(pady="0")
        createButton.configure(relief=GROOVE)
        createButton.configure(text='''Create''')
        def onClick():
            newBranch(bsIDbox.get(), attrtBOX.get(), blIDbox.get())
            top.destroy()
        createButton.configure(command=onClick)




def pToOutput(text):
    output.configure(state=NORMAL)
    output.delete(1.0, "end")
    output.insert("end", text)
    output.configure(state=DISABLED)

def newBranchSet(branchSetID, applyToTectonicRegionType, branchingLevelID):
    global ltData
    global bsData
    global output

    if branchingLevelID == "" or branchingLevelID == " ":
        branchingLevelID = "bl"+str(len(ltData)+1)
    if branchSetID == "" or branchSetID == " ":
        branchSetID = "bs"+str(len(bsData)+1)

    ltData[len(ltData)+1] = {
        "branchingLevelID": branchingLevelID,
        "ltBranch": ltBranch,
        "bsData": bsData
    }
    bsData[len(bsData)+1] = {
        "branchSetID": branchSetID,
        "applyToTectonicRegionType":applyToTectonicRegionType
    }
    ltBranch[len(ltBranch)+1] = {}
    parseOut(ltData)

def newBranch(bsID, gmpe_table, uncertaintyWeight):
    global ltData
    impNum = 0
    bsData5 = ltData[1]["bsData"]
    ltBranch5 = ltData[1]["ltBranch"]
    for x in range(0,len(bsData5)): #get the branchset number
        x = x+1
        y = bsData5[x]
        if y["branchSetID"] == bsID:
            impNum = x
    branchSet = ltBranch5[impNum]
    branchSet[len(branchSet)+1] = {
        "branchSetID": "b"+str(impNum)+str(len(branchSet)+1),
        "text": "GMPETable",
        "gmpe_table": gmpe_table,
        'uncertaintyWeight': uncertaintyWeight
    }
    print("Test -> "+json.dumps(ltData))
    parseOut(ltData)

def deleteObject(type, obj):
    print("branch")



def setoutput(var):
    global output
    output = var
    print('ran?')
class GMPE_File_Editor:
    #newBranchSet("bs1", "test", "bl1")
    #newBranch("bs1", "test", "0.2")
    def __init__(self, top=None):


        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+650+150")
        top.title("GMPE File Editor")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        def export(data):
            toExp = json.dumps(json.dumps(ltData))
            top.filename = filedialog.asksaveasfilename(initialdir = "/",title = "Select file",filetypes = (("XML file","*.xml"), ("all files","*.*")))
            if top.filename == "":
                return 0
            top.filename = top.filename+".xml"
            os.system('python ../gmpe-handler.py -output "'+top.filename+'" -ltd '+toExp)

        self.nBbutton = ttk.Button(top, command=lambda: nbsPopup())
        self.nBbutton.place(relx=0.03, rely=0.84, height=55, width=216)
        self.nBbutton.configure(takefocus="")
        self.nBbutton.configure(text='''New Branch Set''')

        self.nBbutton_1 = ttk.Button(top)
        self.nBbutton_1.place(relx=0.62, rely=0.84, height=55, width=216)
        self.nBbutton_1.configure(takefocus="")
        self.nBbutton_1.configure(text='''New Branch''')
        self.nBbutton_1.configure(command=lambda: nbPopup())

        exButton = Button(top)
        exButton.place(relx=0.03, y=15, height=25, width=66)
        exButton.configure(takefocus="")
        exButton.configure(text='Export')
        exButton.configure(width=66)
        exButton.configure(command=lambda: export(ltData))

        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0, rely=0.11, relheight=0.69, relwidth=1)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font="TkTextFont")
        self.Scrolledtext1.configure(foreground="black")
        self.Scrolledtext1.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext1.configure(highlightcolor="black")
        self.Scrolledtext1.configure(insertbackground="black")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="#c4c4c4")
        self.Scrolledtext1.configure(selectforeground="black")
        self.Scrolledtext1.configure(width=10)
        self.Scrolledtext1.configure(wrap=NONE)
        self.Scrolledtext1.config(state=DISABLED)
        setoutput(self.Scrolledtext1)

        self.nBbutton_2 = ttk.Button(top)
        self.nBbutton_2.place(relx=0.38, rely=0.84, height=55, width=146)
        self.nBbutton_2.configure(takefocus="")
        self.nBbutton_2.configure(text='''Delete''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.38, y=15, height=25, width=144)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''GMPE Editor''')




# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

if __name__ == '__main__':
    vp_start_gui()
